const symptoms=['Сердцебиение','Тревога','Головная боль','Тошнота','Сухость во рту','Изжога','Нет жалоб'];
function renderChips(){const a=today().symptoms||[];$('#chips').innerHTML=symptoms.map(s=>`<button class="chip ${a.includes(s)?'on':''}" data-s="${s}">${s}</button>`).join('');$$('[data-s]').forEach(b=>b.onclick=()=>{const t=today(),s=b.dataset.s;let a=t.symptoms||[];if(s==='Нет жалоб')a=a.includes(s)?[]:[s];else{a=a.filter(x=>x!=='Нет жалоб');a=a.includes(s)?a.filter(x=>x!==s):[...a,s]}t.symptoms=a;save();renderChips()})}
$('#appetite').oninput=e=>$('#av').textContent=e.target.value;$('#saveDay').onclick=()=>{today().appetite=+$('#appetite').value;today().mood=$('#mood').value;save();$('#ds').textContent='Сохранено.';renderCalendar()};
const weights=()=>Object.entries(d.days).filter(([,v])=>Number.isFinite(v.weight)).sort();
const delta=v=>Number.isFinite(v)?`${v<=0?'−':'+'}${Math.abs(v).toFixed(1).replace('.',',')} кг`:'—';
function prior(n){const cut=new Date();cut.setHours(0,0,0,0);cut.setDate(cut.getDate()-n);let out=null;for(const [k,v] of weights())if(new Date(k+'T00:00:00')<=cut)out=v.weight;return out}
function renderWeek(){let h='';for(let i=6;i>=0;i--){const x=new Date();x.setDate(x.getDate()-i);const k=key(x),has=d.days[k]&&Object.keys(d.days[k]).length;h+=`<div class="wd ${has?'has':''} ${k===key()?'today':''}">${new Intl.DateTimeFormat('ru-RU',{weekday:'short'}).format(x).replace('.','')}<b>${x.getDate()}</b></div>`}$('#week').innerHTML=h}
function renderWeight(){const e=weights(),start=Number.isFinite(d.startWeight)?d.startWeight:null,last=e.length?e.at(-1)[1].weight:start,dt=(start!=null&&last!=null)?last-start:null;$('#startWeightView').textContent=start==null?'—':start.toFixed(1).replace('.',',')+' кг';$('#hw').textContent=$('#wn').textContent=last==null?'—':last.toFixed(1).replace('.',',');$('#hd').textContent=dt==null?'Запиши первый вес':delta(dt)+' от старта';const w7=prior(7),w30=prior(30);$('#sw').textContent=$('#ww').textContent=w7==null||last==null?'—':delta(last-w7);$('#sm').textContent=$('#wm').textContent=w30==null||last==null?'—':delta(last-w30);$('#st').textContent=$('#wt').textContent=delta(dt);let p=0;if(d.goalWeight&&start&&last!=null&&d.goalWeight<start)p=Math.max(0,Math.min(100,(start-last)/(start-d.goalWeight)*100));$('#ring').style.setProperty('--p',p);$('#pct').textContent=Math.round(p)+'%';$('#bar').style.width=p+'%';$('#goalTxt').textContent=d.goalWeight&&last!=null?`До цели ${Math.max(0,last-d.goalWeight).toFixed(1).replace('.',',')} кг`:'Задай цель в разделе «Вес»';$('#pt').textContent=d.goalWeight&&start?`Пройдено ${p.toFixed(1).replace('.',',')}% пути к цели`:'Укажите желаемый вес.';$('#gi').value=d.goalWeight||'';const a=e.slice(-10),vals=a.map(x=>x[1].weight);if(vals.length){const mn=Math.min(...vals),mx=Math.max(...vals),rg=Math.max(.1,mx-mn);$('#chart').innerHTML=a.map(([,v])=>`<i style="height:${25+72*(mx-v.weight)/rg}px"></i>`).join('')}else $('#chart').innerHTML='';$('#wh').innerHTML=a.slice().reverse().map(([k,v])=>`<div class="hi"><span>${k.split('-').reverse().join('.')}</span><b>${v.weight.toFixed(1).replace('.',',')} кг</b></div>`).join('')||'<span class="small muted">Пока нет записей.</span>';renderWeek()}
$('#saveW').onclick=()=>{let w=+$('#wi').value,g=+$('#gi').value;if(!(w>=30&&w<=350))return $('#ws').textContent='Проверь значение веса.';w=Math.round(w*10)/10;today().weight=w;if(!Number.isFinite(d.startWeight))d.startWeight=w;if(g>=30&&g<=350)d.goalWeight=g;save();$('#ws').textContent='Вес сохранён.';renderWeight();renderCalendar()};
function renderVitals(){const a=d.vitals.slice(-8).reverse();$('#vh').innerHTML=a.map(v=>`<div class="hi"><span>${v.date.split('-').reverse().join('.')} ${v.time||''}</span><b>${v.sys}/${v.dia} · ${v.pulse}</b></div>`).join('')||'<span class="small muted">Пока нет измерений.</span>'}
$('#saveV').onclick=()=>{const s=+$('#sys').value,q=+$('#dia').value,p=+$('#pulse').value;if(!(s>=50&&s<=260&&q>=30&&q<=180&&p>=25&&p<=250))return $('#vs').textContent='Проверь значения.';d.vitals.push({date:key(),sys:s,dia:q,pulse:p,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});save();$('#vs').textContent='Сохранено.';renderVitals();renderCalendar()};
function renderCalendar(){const n=new Date(),y=n.getFullYear(),m=n.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h='<i></i>'.repeat(first);for(let x=1;x<=last;x++){const k=`${y}-${pad(m+1)}-${pad(x)}`,has=d.days[k]&&Object.keys(d.days[k]).length;h+=`<div class="day ${has?'has':''} ${k===key()?'today':''}">${x}</div>`}$('#cal').innerHTML=h}
$('#saveN').onclick=()=>{today().note=$('#note').value.trim();save();$('#ns').textContent='Заметка сохранена.';renderCalendar()};
$('#exp').onclick=()=>{const b=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='moy-ritm-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#imp').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!x.days||!x.meds)throw 0;d={...structuredClone(D),...x};save();init();$('#bs').textContent='Данные восстановлены.'}catch{$('#bs').textContent='Файл не удалось прочитать.'}};
$('#reset').onclick=()=>{if(confirm('Удалить все локальные записи?')){localStorage.removeItem(K);d=structuredClone(D);save();init()}};
