let rxWindow=7;
const rx=()=>today().reduxin||(today().reduxin={});
function renderRx(){const r=rx();$('#rxApp').value=Number.isFinite(r.appetite)?r.appetite:(today().appetite??5);$('#rxAppVal').textContent=$('#rxApp').value;$('#rxSleep').value=Number.isFinite(r.sleep)?r.sleep:'';$('#rxSleepQ').value=r.sleepQuality||'';$('#rxMood').value=r.mood||today().mood||'';$('#rxSys').value=r.sys||'';$('#rxDia').value=r.dia||'';$('#rxPulse').value=r.pulse||'';$('#rxNote').value=r.note||'';$$('[data-rxs]').forEach(c=>c.checked=(r.symptoms||[]).includes(c.dataset.rxs));$('#rxTaken').textContent=r.taken?'Принят ✓':'Не отмечен';$('#rxBadge').textContent=Object.keys(r).length?'Сегодня заполнено':'Сегодня не заполнено'}
$('#rxTaken').onclick=()=>{rx().taken=!rx().taken;save();renderRx()};$('#rxApp').oninput=e=>$('#rxAppVal').textContent=e.target.value;
$('#saveRx').onclick=()=>{const r=rx(),sl=+$('#rxSleep').value,s=+$('#rxSys').value,q=+$('#rxDia').value,p=+$('#rxPulse').value;r.appetite=+$('#rxApp').value;r.sleep=sl>=0&&sl<=24?sl:null;r.sleepQuality=$('#rxSleepQ').value;r.mood=$('#rxMood').value;r.symptoms=$$('[data-rxs]').filter(x=>x.checked).map(x=>x.dataset.rxs);r.note=$('#rxNote').value.trim();if(s>=50&&s<=260&&q>=30&&q<=180){r.sys=s;r.dia=q}else{delete r.sys;delete r.dia}if(p>=25&&p<=250)r.pulse=p;else delete r.pulse;today().appetite=r.appetite;if(r.mood)today().mood=r.mood;save();$('#rxStatus').textContent='Запись сохранена.';renderRx();renderRxSummary();renderHome();renderCalendar()};
function rxEntries(n){const cut=new Date();cut.setHours(0,0,0,0);cut.setDate(cut.getDate()-(n-1));return Object.entries(d.days).filter(([k,v])=>v.reduxin&&Object.keys(v.reduxin).length&&new Date(k+'T00:00:00')>=cut).sort()}
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
function renderRxSummary(){const a=rxEntries(rxWindow),apps=a.map(([,v])=>v.reduxin.appetite).filter(Number.isFinite),sleep=a.map(([,v])=>v.reduxin.sleep).filter(Number.isFinite),pulse=a.map(([,v])=>v.reduxin.pulse).filter(Number.isFinite),bp=a.map(([,v])=>v.reduxin).filter(x=>Number.isFinite(x.sys)&&Number.isFinite(x.dia)),sym={};a.forEach(([,v])=>(v.reduxin.symptoms||[]).forEach(x=>sym[x]=(sym[x]||0)+1));const aa=avg(apps),as=avg(sleep),ap=avg(pulse),bs=avg(bp.map(x=>x.sys)),bd=avg(bp.map(x=>x.dia));$('#rxAvgApp').textContent=aa==null?'—':aa.toFixed(1).replace('.',',')+'/10';$('#rxAvgSleep').textContent=as==null?'—':as.toFixed(1).replace('.',',')+' ч';$('#rxDays').textContent=a.length;$('#rxSymptoms').textContent=Object.values(sym).reduce((s,x)=>s+x,0);$('#rxReport').textContent=`Сводка за ${rxWindow} дней\nЗаполнено дней: ${a.length}\nСредний аппетит: ${aa==null?'нет данных':aa.toFixed(1)}\nСредний сон: ${as==null?'нет данных':as.toFixed(1)+' ч'}\nСредний пульс: ${ap==null?'нет данных':Math.round(ap)}\nСреднее давление: ${bs==null?'нет данных':Math.round(bs)+'/'+Math.round(bd)}\nОщущения: ${Object.entries(sym).map(([k,v])=>k+' — '+v).join(', ')||'не отмечались'}`;$('#rxChartRange').textContent=rxWindow+' дней';const chart=(id,vals,max)=>{const el=$(id);if(!vals.length)return el.innerHTML='<div class="chartEmpty">Недостаточно данных</div>';const w=320,h=100,p=10,pts=vals.map((v,i)=>`${p+i*(w-2*p)/Math.max(1,vals.length-1)},${h-p-(v/max)*(h-2*p)}`).join(' ');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}"><polyline points="${pts}" fill="none" stroke="#795fd0" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`};chart('#rxAppChart',apps,10);chart('#rxSleepChart',sleep,12);const vv=pulse.length?pulse:bp.map(x=>x.sys);chart('#rxVitalChart',vv,Math.max(180,...vv));$('#rxAppTrend').textContent=aa==null?'—':aa.toFixed(1);$('#rxSleepTrend').textContent=as==null?'—':as.toFixed(1)+' ч';$('#rxVitalTrend').textContent=ap==null?'—':Math.round(ap)+' уд/мин';$('#rxInsight').textContent=a.length<3?'Нужно несколько дней данных для сравнения.':'Записей достаточно, чтобы наблюдать личные тенденции. Это не медицинский вывод.'}
$('#rx7').onclick=()=>{rxWindow=7;$('#rx7').classList.add('on');$('#rx30').classList.remove('on');renderRxSummary()};$('#rx30').onclick=()=>{rxWindow=30;$('#rx30').classList.add('on');$('#rx7').classList.remove('on');renderRxSummary()};$('#copyRx').onclick=async()=>{try{await navigator.clipboard.writeText($('#rxReport').textContent);$('#rxStatus').textContent='Отчёт скопирован.'}catch{$('#rxStatus').textContent='Скопируйте текст вручную.'}};
