function renderSteps(){const s=Number.isFinite(today().steps)?today().steps:0,g=d.stepsGoal||8000,p=Math.min(100,s/g*100);$('#stepsNow').textContent=s.toLocaleString('ru-RU');$('#stepsGoalTxt').textContent=g.toLocaleString('ru-RU');$('#stepsGoal').value=g;$('#stepsInput').value=Number.isFinite(today().steps)?today().steps:'';$('#stepsRing').style.setProperty('--p',p);$('#stepsPct').textContent=Math.round(p)+'%';$('#stepsBadge').textContent=Math.round(p)+'% цели';const vals=[];for(let i=6;i>=0;i--){const x=new Date();x.setDate(x.getDate()-i);vals.push(d.days[key(x)]?.steps||0)}$('#stepsAvg').textContent=Math.round(vals.reduce((a,b)=>a+b,0)/7).toLocaleString('ru-RU');$('#stepsBest').textContent=Math.max(...vals).toLocaleString('ru-RU');$('#stepsDoneDays').textContent=vals.filter(x=>x>=g).length+'/7';const mx=Math.max(g,...vals,1);$('#stepsChart').innerHTML=vals.map(v=>`<i style="height:${Math.max(5,100*v/mx)}px"></i>`).join('')}
$('#saveSteps').onclick=()=>{const v=+$('#stepsInput').value,g=+$('#stepsGoal').value;if(!(v>=0&&v<=100000))return $('#stepsStatus').textContent='Проверь количество шагов.';if(g>=500&&g<=100000)d.stepsGoal=Math.round(g);today().steps=Math.round(v);save();$('#stepsStatus').textContent='Шаги сохранены.';renderSteps();renderCalendar()};
const FOOD={'гречка':[110,4.2,1.1,21.3],'рис':[130,2.7,.3,28.2],'картофель':[82,2,.4,16.7],'картошка':[82,2,.4,16.7],'куриная грудка':[165,31,3.6,0],'курица':[190,27,8,0],'индейка':[135,29,1.6,0],'говядина':[250,26,15,0],'свинина':[242,27,14,0],'котлета':[250,17,18,9],'огурец':[15,.7,.1,3.6],'помидор':[18,.9,.2,3.9],'яблоко':[52,.3,.2,14],'банан':[89,1.1,.3,23],'сыр':[350,25,27,2],'творог':[121,17,5,3],'яйцо':[155,13,11,1.1],'кефир':[53,3,2.5,4],'молоко':[60,3.2,3.2,4.7],'хлеб':[250,8,3,49],'овсянка':[71,2.5,1.5,12],'макароны':[131,5,1.1,25],'лосось':[208,20,13,0],'рыба':[140,20,6,0],'авокадо':[160,2,15,9]};
let pending=null;
function calcFood(text){const items=[];for(const part of text.toLowerCase().split(/[,;]|\s+и\s+/)){const m=part.match(/(.+?)\s+(\d+(?:[.,]\d+)?)\s*(?:г|гр|грамм(?:а|ов)?)(?:\b|$)/i);if(!m)continue;const grams=parseFloat(m[2].replace(',','.')),name=m[1].trim();const k=Object.keys(FOOD).sort((a,b)=>b.length-a.length).find(x=>name.includes(x));if(!k)continue;const [kc,p,f,c]=FOOD[k],q=grams/100;items.push({name:k,grams,kcal:kc*q,protein:p*q,fat:f*q,carbs:c*q})}if(!items.length)return null;const sum=k=>items.reduce((s,x)=>s+x[k],0);return{items,total:{kcal:sum('kcal'),protein:sum('protein'),fat:sum('fat'),carbs:sum('carbs')},note:'Приблизительный расчёт по средним значениям.'}}
function showFood(r){pending=r;if(!r)return $('#foodResultCard').hidden=true;$('#foodResult').innerHTML=r.items.map(x=>`<div class="foodItem"><div><b>${esc(x.name)}</b><div class="mac">${Math.round(x.grams)} г · Б ${x.protein.toFixed(1)} · Ж ${x.fat.toFixed(1)} · У ${x.carbs.toFixed(1)}</div></div><b>${Math.round(x.kcal)} ккал</b></div>`).join('')+`<div class="note">${esc(r.note)}</div>`;$('#foodResultCard').hidden=false}
$('#analyzeFood').onclick=()=>{const r=calcFood($('#foodText').value.trim());if(r){showFood(r);$('#foodStatus').textContent='Готово. Проверь граммы.'}else $('#foodStatus').textContent='Не смогла распознать. Скажи, например: «гречка 150 граммов, курица 120 граммов».'};
$('#saveFood').onclick=()=>{if(!pending)return;const t=today();t.food=t.food||[];t.food.push({...pending,at:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});save();pending=null;$('#foodResultCard').hidden=true;$('#foodText').value='';$('#foodStatus').textContent='Добавлено в дневник.';renderFood();renderCalendar()};
$('#foodPhoto').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f);$('#photoImg').src=u;$('#photoPreview').hidden=false;$('#foodStatus').textContent='Фото добавлено. На GitHub Pages фото-анализ ИИ пока не подключён; уточни продукты и граммы голосом.'};$('#removePhoto').onclick=()=>{$('#photoPreview').hidden=true;$('#foodPhoto').value=''};
function renderFood(){const a=today().food||[],sum=k=>a.reduce((s,r)=>s+(r.total?.[k]||0),0),kc=sum('kcal');$('#calBadge').textContent=Math.round(kc)+' ккал';$('#foodTotal').textContent=Math.round(kc)+' ккал';$('#foodProtein').textContent=sum('protein').toFixed(1)+' г';$('#foodFat').textContent=sum('fat').toFixed(1)+' г';$('#foodCarbs').textContent=sum('carbs').toFixed(1)+' г';$('#foodHistory').innerHTML=a.slice().reverse().map(r=>`<div class="hi"><span>${r.at||''} · ${r.items.map(x=>x.name).join(', ')}</span><b>${Math.round(r.total.kcal)} ккал</b></div>`).join('')||'<span class="small muted">Сегодня питание ещё не записано.</span>'}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=null;if(SR){rec=new SR();rec.lang='ru-RU';rec.interimResults=false;rec.onstart=()=>{$('#voiceFood').textContent='⏹ Слушаю…';$('#voiceFood').classList.add('listening')};rec.onend=()=>{$('#voiceFood').textContent='🎙️ Говорить';$('#voiceFood').classList.remove('listening')};rec.onresult=e=>{const t=e.results[0][0].transcript;$('#foodText').value=($('#foodText').value.trim()?$('#foodText').value.trim()+', ':'')+t;$('#voiceHint').textContent='Распознано: '+t;$('#analyzeFood').click()};rec.onerror=()=>$('#voiceHint').textContent='Не удалось распознать речь. Можно использовать микрофон клавиатуры.'}else{$('#voiceFood').disabled=true;$('#voiceHint').textContent='Голосовой ввод браузером не поддерживается. Используй микрофон клавиатуры.'}$('#voiceFood').onclick=()=>{try{rec?.start()}catch{rec?.stop()}};
function renderHome(){const t=today();$('#appetite').value=Number.isFinite(t.appetite)?t.appetite:5;$('#av').textContent=$('#appetite').value;$('#mood').value=t.mood||'';$('#note').value=t.note||''}
function init(){renderHome();renderMeds();renderChips();renderWeight();renderVitals();renderCalendar();renderRx();renderRxSummary();renderSteps();renderFood()}init();navigator.serviceWorker?.register('./sw.js').catch(()=>{});
